---
  - hosts: all

    become: yes
    become_method: sudo
    become_user: root

    tasks: 
      - name: Install Apache httpd
        yum: name=httpd state=latest

      - name: Insert message into index.html
        shell: echo 'Nice work! Message inserted succesfully' > /var/www/html/index.html
      
      - name: Activate httpd
        service: name=httpd state=restarted enabled=yes 
